"""auto

Revision ID: 93f840ff53ba
Revises: cd761b5b8da3
Create Date: 2026-03-09 00:51:51.002980
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f840ff53ba'
down_revision: Union[str, None] = 'cd761b5b8da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_sections', sa.Column('audio_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_sections', 'audio_url')
    # ### end Alembic commands ###
